name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set go 1.11 module
      run: GO111MODULE=on

    - name: Build nuklear
      run: ./build.sh nuklear
      id: nuklear

    - name: Build cli
      run: ./build.sh cli
      id: cli

    - name: Build terminal
      run: ./build.sh terminal
      id: terminal

  
